Seagrass Protection:
    outputDir: /mnt/c/Users/neilm/Documents/Drawdown/glass-wing/solutions/solution/seagrassprotection/
    excelFile: /mnt/c/Users/neilm/Documents/Drawdown/Excel Files/Updated_Oceans/Drawdown_RRS-BIOSEQProtect_Model_v1.1b_Coastal_Wetlands(Seagrasses)_JULY2021-final.xlsm
    