Macroalgae Restoration:
    outputDir: /mnt/c/Users/neilm/Documents/Drawdown/glass-wing/solutions/solution/macroalgaerestoration/
    excelFile: /mnt/c/Users/neilm/Documents/Drawdown/Excel Files/Updated_Oceans/Macroalgae Restoration_Ocean Model_AUGUST2021_After Reviews.xlsm
    