Macroalgae Protection:
    outputDir: /mnt/c/Users/neilm/Documents/Drawdown/glass-wing/solutions/solution/macroalgaeprotection/
    excelFile: /mnt/c/Users/neilm/Documents/Drawdown/Excel Files/Macroalgae protection_Ocean Model_March2021.xlsm
    