Seafloor Protection:
    outputDir: /mnt/c/Users/neilm/Documents/Drawdown/glass-wing/solutions/solution/seafloorprotection/
    excelFile: /mnt/c/Users/neilm/Documents/Drawdown/Excel Files/Updated_Oceans/Seafloor_Protection_Ocean Model_JULY2021.xlsm
    