

ScenariosFile: scenario_inputs.json
PDSAdoptionFile: unit_adoption_data/custom_pds_adoption.json
REFAdoptionFile: unit_adoption_data/custom_ref_adoption.json
BaseYear: 2015
StartYear: 2020
EndYear: 2050
TotalArea: 240
RequiredPythonVersionMinimum: 3.9.5
