

ScenariosFile: scenario_inputs.json
PDSAdoptionFile: custom_pds_adoption.json
REFAdoptionFile: custom_ref_adoption.json
BaseYear: 2015
StartYear: 2020
EndYear: 2050
TotalArea: 240
RequiredPythonVersionMinimum: 3.9.5
